language: java
jdk:
  - oraclejdk7
install:
  - true
script:
  - travis_wait ./gradlew $TASK --continue
env:
  global:
    - TERM=dumb
  matrix:
    - TASK=pullRequestValidation
    - TASK=check
branches:
  only:
    - master
    - travis-integration-test
sudo: false
